apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: june23-test-1-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june23-test-1-database
  name: june23-test-1-database
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/instance: june23-test-1-database
